// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0tvfyGsfO5gxJ0o4dyUHlwEMS6uXh5hM',
    appId: '1:467890599504:web:ac47b544cef0fa014c8355',
    messagingSenderId: '467890599504',
    projectId: 'bmi-app-17fa0',
    authDomain: 'bmi-app-17fa0.firebaseapp.com',
    storageBucket: 'bmi-app-17fa0.appspot.com',
    measurementId: 'G-7QG5TG3T2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPkVByfxZt1EBYLd-sGIqgyw7fdAw11Q4',
    appId: '1:467890599504:android:e4c3aa15504afe374c8355',
    messagingSenderId: '467890599504',
    projectId: 'bmi-app-17fa0',
    storageBucket: 'bmi-app-17fa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiY7FBNWim38PCJOvoRBHz40haVw3ovGI',
    appId: '1:467890599504:ios:42640264d39994c34c8355',
    messagingSenderId: '467890599504',
    projectId: 'bmi-app-17fa0',
    storageBucket: 'bmi-app-17fa0.appspot.com',
    iosBundleId: 'com.example.bmiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiY7FBNWim38PCJOvoRBHz40haVw3ovGI',
    appId: '1:467890599504:ios:42640264d39994c34c8355',
    messagingSenderId: '467890599504',
    projectId: 'bmi-app-17fa0',
    storageBucket: 'bmi-app-17fa0.appspot.com',
    iosBundleId: 'com.example.bmiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0tvfyGsfO5gxJ0o4dyUHlwEMS6uXh5hM',
    appId: '1:467890599504:web:2228e6510ffcf8e74c8355',
    messagingSenderId: '467890599504',
    projectId: 'bmi-app-17fa0',
    authDomain: 'bmi-app-17fa0.firebaseapp.com',
    storageBucket: 'bmi-app-17fa0.appspot.com',
    measurementId: 'G-9KG33GJNSL',
  );
}
